version: "3.8"

services:
  free5gc-upf:
    container_name: upf
    image: free5gc/upf:v4.0.1
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./custom_configs/upfcfg.yaml:/free5gc/config/upfcfg.yaml
      - ./custom_configs/upf-iptables.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        aliases:
          - upf.free5gc.org

  db:
    container_name: mongodb
    image: mongo:3.6.8
    command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      - dbdata:/data/db
    networks:
      privnet:
        aliases:
          - db

  free5gc-nrf:
    container_name: nrf
    image: free5gc/nrf:v4.0.1
    command: ./nrf -c ./config/nrfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./custom_configs/nrfcfg.yaml:/free5gc/config/nrfcfg.yaml
      - ./custom_configs/cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - nrf.free5gc.org
    depends_on:
      - db

  free5gc-amf:
    container_name: amf
    image: free5gc/amf:v4.0.1
    command: ./amf -c ./config/amfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./custom_configs/amfcfg.yaml:/free5gc/config/amfcfg.yaml
      - ./custom_configs/cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        ipv4_address: 10.100.200.16
        aliases:
          - amf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-ausf:
    container_name: ausf
    image: free5gc/ausf:v4.0.1
    command: ./ausf -c ./config/ausfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./custom_configs/ausfcfg.yaml:/free5gc/config/ausfcfg.yaml
      - ./custom_configs/cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - ausf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-nssf:
    container_name: nssf
    image: free5gc/nssf:v4.0.1
    command: ./nssf -c ./config/nssfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./custom_configs/nssfcfg.yaml:/free5gc/config/nssfcfg.yaml
      - ./custom_configs/cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - nssf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-pcf:
    container_name: pcf
    image: free5gc/pcf:v4.0.1
    command: ./pcf -c ./config/pcfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./custom_configs/pcfcfg.yaml:/free5gc/config/pcfcfg.yaml
      - ./custom_configs/cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - pcf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-smf:
    container_name: smf
    image: free5gc/smf:v4.0.1
    command: ./smf -c ./config/smfcfg.yaml -u ./config/uerouting.yaml
    expose:
      - "8000"
    volumes:
      - ./custom_configs/smfcfg.yaml:/free5gc/config/smfcfg.yaml
      - ./custom_configs/uerouting.yaml:/free5gc/config/uerouting.yaml
      - ./custom_configs/cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - smf.free5gc.org
    depends_on:
      - free5gc-nrf
      - free5gc-upf

  free5gc-udm:
    container_name: udm
    image: free5gc/udm:v4.0.1
    command: ./udm -c ./config/udmcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./custom_configs/udmcfg.yaml:/free5gc/config/udmcfg.yaml
      - ./custom_configs/cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - udm.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-udr:
    container_name: udr
    image: free5gc/udr:v4.0.1
    command: ./udr -c ./config/udrcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./custom_configs/udrcfg.yaml:/free5gc/config/udrcfg.yaml
      - ./custom_configs/cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - udr.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-chf:
    container_name: chf
    image: free5gc/chf:v4.0.1
    command: ./chf -c ./config/chfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./custom_configs/chfcfg.yaml:/free5gc/config/chfcfg.yaml
      - ./custom_configs/cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - chf.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-webui:
    container_name: webui
    image: free5gc/webui:v4.0.1
    command: ./webui -c ./config/webuicfg.yaml
    expose:
      - "2121"
    volumes:
      - ./custom_configs/webuicfg.yaml:/free5gc/config/webuicfg.yaml
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - webui
    ports:
      - "5000:5000"
    depends_on:
      - db
      - free5gc-nrf

  ueransim-gnb:
    container_name: ueransim-gnb
    image: free5gc/ueransim:latest
    command: ./nr-gnb -c ./config/gnb.yaml
    volumes:
      - ./custom_configs/gnb.yaml:/ueransim/config/gnb.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      privnet:
        aliases:
          - gnb.free5gc.org
    depends_on:
      - free5gc-amf
      - free5gc-upf

  ueransim-ue1:
    container_name: ueransim-ue1
    image: free5gc/ueransim:latest
    command: ./nr-ue -c ./config/ue1.yaml 
    volumes:
      - ./custom_configs/ue1.yaml:/ueransim/config/ue1.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      privnet:
        aliases:
          - ue1.free5gc.org
    depends_on:
      - ueransim-gnb

  ueransim-ue2:
    container_name: ueransim-ue2
    image: free5gc/ueransim:latest
    command: ./nr-ue -c ./config/ue2.yaml
    volumes:
      - ./custom_configs/ue2.yaml:/ueransim/config/ue2.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      privnet:
        aliases:
          - ue2.free5gc.org
    depends_on:
      - ueransim-gnb

  free5gc-n3iwf:
    container_name: n3iwf
    image: free5gc/n3iwf:v4.0.1
    command: ./n3iwf -c ./config/n3iwfcfg.yaml
    volumes:
      - ./custom_configs/n3iwfcfg.yaml:/free5gc/config/n3iwfcfg.yaml
      - ./custom_configs/n3iwf-ipsec.sh:/free5gc/n3iwf-ipsec.sh 
    environment:
      GIN_MODE: release
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        ipv4_address: 10.100.200.15
        aliases:
          - n3iwf.free5gc.org
    depends_on:
      - free5gc-amf
      - free5gc-smf
      - free5gc-upf

  # ---- Monitoring Services ----
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2 #
    container_name: cadvisor
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring_configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    depends_on:
      - cadvisor

networks:
  privnet:
    ipam:
      driver: default
      config:
        - subnet: 10.100.200.0/24
    driver_opts:
      com.docker.network.bridge.name: br-free5gc

volumes:
  dbdata: {}
  prometheus_data: {}